// This file is auto-generated by scripts/generate-content-manifest.ts
// Do not edit manually - run `npm run generate-manifest` to update

export interface ContentManifest {
  tests: Record<string, number[]>
  roleplays: Record<string, Record<string, number[]>>
}

export const contentManifest: ContentManifest = {
  "tests": {
    "business-administration": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11
    ],
    "entrepreneurship": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ],
    "finance": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15
    ],
    "hospitality-tourism": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13
    ],
    "marketing": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14
    ]
  },
  "roleplays": {
    "business-administration": {
      "BLTDM": [
        1,
        2,
        3,
        4,
        5
      ],
      "HRM": [
        1,
        2,
        3,
        4
      ]
    },
    "entrepreneurship": {
      "ENT": [
        1,
        2,
        3,
        4,
        5,
        6
      ],
      "ETDM": [
        1,
        2,
        3,
        4,
        5
      ]
    },
    "finance": {
      "ACT": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ],
      "BFS": [
        1,
        2,
        3,
        4
      ],
      "FTDM": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ]
    },
    "hospitality-tourism": {
      "HLM": [
        1,
        2,
        3,
        4,
        5,
        6
      ],
      "HTDM": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8
      ],
      "QSRM": [
        1,
        2,
        3
      ],
      "RFSM": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ],
      "TTDM": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11
      ]
    },
    "marketing": {
      "AAM": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ],
      "ASM": [
        1,
        2,
        3,
        4,
        5,
        6
      ],
      "BSM": [
        1,
        2,
        3,
        4,
        5,
        6
      ],
      "BTDM": [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15
      ],
      "FMS": [
        1,
        2,
        3,
        4,
        5,
        6
      ],
      "MCS": [
        1,
        2,
        3,
        4,
        5,
        6
      ],
      "MTDM": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ],
      "RMS": [
        1,
        2,
        3,
        4,
        5
      ],
      "SEM": [
        1,
        2,
        3,
        4,
        5
      ],
      "STDM": [
        1,
        2,
        3,
        4,
        5,
        6,
        7
      ]
    }
  }
}
