import { writeFileSync, readdirSync, existsSync } from "fs"
import { join } from "path"

interface ContentManifest {
  tests: Record<string, number[]>
  roleplays: Record<string, Record<string, number[]>>
  roleplayDirs: Record<string, Record<string, string>>
}

const manifest: ContentManifest = {
  tests: {},
  roleplays: {},
  roleplayDirs: {},
}

const clusters = [
  "business-administration",
  "entrepreneurship",
  "finance",
  "hospitality-tourism",
  "marketing",
]

// Generate tests manifest
for (const clusterId of clusters) {
  const testDir = join(process.cwd(), "public", "clusters", clusterId, "tests")
  if (existsSync(testDir)) {
    const files = readdirSync(testDir)
    const testNumbers = files
      .filter((file) => file.startsWith("test-") && file.endsWith(".pdf"))
      .map((file) => {
        const match = file.match(/test-(\d+)\.pdf/)
        return match ? parseInt(match[1], 10) : null
      })
      .filter((num): num is number => num !== null)
      .sort((a, b) => a - b)
    manifest.tests[clusterId] = testNumbers
  }
}

// Generate roleplays manifest
for (const clusterId of clusters) {
  const roleplayBaseDir = join(process.cwd(), "public", "clusters", clusterId, "roleplays")
  if (existsSync(roleplayBaseDir)) {
    const eventDirs = readdirSync(roleplayBaseDir, { withFileTypes: true })
      .filter((dir) => dir.isDirectory())
      .map((dir) => dir.name)

    for (const eventDir of eventDirs) {
      const roleplayDir = join(roleplayBaseDir, eventDir)
      const files = readdirSync(roleplayDir)
      const roleplayNumbers = files
        .filter((file) => file.startsWith("roleplay-") && file.endsWith(".pdf"))
        .map((file) => {
          const match = file.match(/roleplay-(\d+)\.pdf/)
          return match ? parseInt(match[1], 10) : null
        })
        .filter((num): num is number => num !== null)
        .sort((a, b) => a - b)

      if (!manifest.roleplays[clusterId]) {
        manifest.roleplays[clusterId] = {}
      }
      if (!manifest.roleplayDirs[clusterId]) {
        manifest.roleplayDirs[clusterId] = {}
      }
      const eventCodeUpper = eventDir.trim().toUpperCase()
      manifest.roleplays[clusterId][eventCodeUpper] = roleplayNumbers
      manifest.roleplayDirs[clusterId][eventCodeUpper] = eventDir // Store actual directory name
    }
  }
}

// Write manifest file as TypeScript
const manifestPath = join(process.cwd(), "data", "content-manifest.ts")
const manifestContent = `// This file is auto-generated by scripts/generate-content-manifest.ts
// Do not edit manually - run \`npm run generate-manifest\` to update

export interface ContentManifest {
  tests: Record<string, number[]>
  roleplays: Record<string, Record<string, number[]>>
  roleplayDirs: Record<string, Record<string, string>>
}

export const contentManifest: ContentManifest = ${JSON.stringify(manifest, null, 2)}
`
writeFileSync(manifestPath, manifestContent)
console.log("Content manifest generated successfully!")
console.log(`Tests:`, Object.keys(manifest.tests).length, "clusters")
console.log(`Roleplays:`, Object.keys(manifest.roleplays).length, "clusters")

